// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	command.proto
	login.proto

It has these top-level messages:
	C2SCommand
	S2CCommand
	C2SConnect
	S2CConnect
	C2SLogin
	S2CLogin
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type C2SCommand struct {
	Command          *int32 `protobuf:"varint,1,req,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2SCommand) Reset()                    { *m = C2SCommand{} }
func (m *C2SCommand) String() string            { return proto1.CompactTextString(m) }
func (*C2SCommand) ProtoMessage()               {}
func (*C2SCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2SCommand) GetCommand() int32 {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return 0
}

type S2CCommand struct {
	Command          *int32 `protobuf:"varint,1,req,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2CCommand) Reset()                    { *m = S2CCommand{} }
func (m *S2CCommand) String() string            { return proto1.CompactTextString(m) }
func (*S2CCommand) ProtoMessage()               {}
func (*S2CCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2CCommand) GetCommand() int32 {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return 0
}

func init() {
	proto1.RegisterType((*C2SCommand)(nil), "proto.C2SCommand")
	proto1.RegisterType((*S2CCommand)(nil), "proto.S2CCommand")
}

func init() { proto1.RegisterFile("command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 72 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xb2, 0x5c,
	0x5c, 0xce, 0x46, 0xc1, 0xce, 0x10, 0x29, 0x21, 0x7e, 0x2e, 0x76, 0xa8, 0x2a, 0x09, 0x46, 0x05,
	0x26, 0x0d, 0x56, 0x90, 0x74, 0xb0, 0x91, 0x33, 0x2e, 0x69, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa1, 0xf4, 0xbe, 0xba, 0x54, 0x00, 0x00, 0x00,
}
