// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C2SConnect struct {
	Hello            *string `protobuf:"bytes,1,req,name=hello" json:"hello,omitempty"`
	Account          *string `protobuf:"bytes,2,req,name=account" json:"account,omitempty"`
	Password         *string `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SConnect) Reset()                    { *m = C2SConnect{} }
func (m *C2SConnect) String() string            { return proto1.CompactTextString(m) }
func (*C2SConnect) ProtoMessage()               {}
func (*C2SConnect) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *C2SConnect) GetHello() string {
	if m != nil && m.Hello != nil {
		return *m.Hello
	}
	return ""
}

func (m *C2SConnect) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *C2SConnect) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type S2CConnect struct {
	Result           *int32  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	Server           *string `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Port             *int32  `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Seed             *string `protobuf:"bytes,4,opt,name=seed,def=" json:"seed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CConnect) Reset()                    { *m = S2CConnect{} }
func (m *S2CConnect) String() string            { return proto1.CompactTextString(m) }
func (*S2CConnect) ProtoMessage()               {}
func (*S2CConnect) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *S2CConnect) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *S2CConnect) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *S2CConnect) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *S2CConnect) GetSeed() string {
	if m != nil && m.Seed != nil {
		return *m.Seed
	}
	return ""
}

type C2SLogin struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	Server           *string `protobuf:"bytes,3,req,name=server" json:"server,omitempty"`
	Seed             *string `protobuf:"bytes,4,req,name=seed" json:"seed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SLogin) Reset()                    { *m = C2SLogin{} }
func (m *C2SLogin) String() string            { return proto1.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()               {}
func (*C2SLogin) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *C2SLogin) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *C2SLogin) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *C2SLogin) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *C2SLogin) GetSeed() string {
	if m != nil && m.Seed != nil {
		return *m.Seed
	}
	return ""
}

type S2CLogin struct {
	Result           *int32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2CLogin) Reset()                    { *m = S2CLogin{} }
func (m *S2CLogin) String() string            { return proto1.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()               {}
func (*S2CLogin) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *S2CLogin) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
	proto1.RegisterType((*C2SConnect)(nil), "proto.C2SConnect")
	proto1.RegisterType((*S2CConnect)(nil), "proto.S2CConnect")
	proto1.RegisterType((*C2SLogin)(nil), "proto.C2SLogin")
	proto1.RegisterType((*S2CLogin)(nil), "proto.S2CLogin")
}

func init() { proto1.RegisterFile("login.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0x3d, 0xaf, 0xc2, 0x20,
	0x14, 0x86, 0x2f, 0xfd, 0xb8, 0xb7, 0x3d, 0xd7, 0xaf, 0x30, 0x11, 0xa7, 0xa6, 0x53, 0x27, 0x07,
	0x46, 0x07, 0x17, 0x36, 0x75, 0xe3, 0x17, 0x34, 0x2d, 0x51, 0x13, 0xc2, 0x69, 0x80, 0xea, 0xdf,
	0x37, 0x50, 0x8d, 0x46, 0x27, 0xc2, 0xfb, 0xe6, 0x3c, 0xef, 0x03, 0xff, 0x1a, 0x4f, 0x17, 0xb3,
	0x19, 0x2c, 0x7a, 0xa4, 0x79, 0x7c, 0xea, 0x1d, 0x80, 0xe0, 0x52, 0xa0, 0x31, 0xaa, 0xf3, 0x74,
	0x0e, 0xf9, 0x59, 0x69, 0x8d, 0x8c, 0x54, 0x49, 0x53, 0xd2, 0x25, 0xfc, 0xb5, 0x5d, 0x87, 0xa3,
	0xf1, 0x2c, 0x89, 0xc1, 0x0a, 0x8a, 0xa1, 0x75, 0xee, 0x86, 0xb6, 0x67, 0x69, 0x48, 0xea, 0x3d,
	0x80, 0xe4, 0xe2, 0x79, 0xbf, 0x80, 0x5f, 0xab, 0xdc, 0xa8, 0x7d, 0x04, 0xe4, 0xe1, 0xef, 0x94,
	0xbd, 0x2a, 0xcb, 0x92, 0x8a, 0x34, 0x25, 0x9d, 0x41, 0x36, 0xa0, 0xf5, 0x2c, 0xad, 0x48, 0x6c,
	0x33, 0xa7, 0x54, 0xcf, 0xb2, 0xd0, 0x6d, 0x7f, 0xea, 0x03, 0x14, 0x82, 0xcb, 0x63, 0x90, 0x7c,
	0x9f, 0x26, 0x5f, 0xd3, 0x93, 0xcc, 0x0b, 0x1e, 0x55, 0x02, 0xfc, 0x81, 0x0b, 0x62, 0x6b, 0x28,
	0x24, 0x17, 0x13, 0xec, 0x43, 0xeb, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xc7, 0x7b, 0xd7, 0x09,
	0x01, 0x00, 0x00,
}
